language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t filfran/docker-react-example -f Dockerfile.dev .

script:
  - docker run -e CI=true filfran/docker-react-example npm run test -- --coverage
